[build]
builder = "nixpacks"

[deploy]
startCommand = "FLASK_APP=wsgi.py flask db stamp 0001 && FLASK_APP=wsgi.py flask db upgrade && gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/health"
healthcheckTimeout = 100
