"""initial

Revision ID: 0001
Revises: 
Create Date: 2026-05-28 15:03:36.253136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('content_raw', sa.Text(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('access_tier', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('subject_area', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('student_grade', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('themes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color_primary', sa.String(length=7), nullable=False),
    sa.Column('color_secondary', sa.String(length=7), nullable=False),
    sa.Column('color_accent', sa.String(length=7), nullable=False),
    sa.Column('color_bg', sa.String(length=7), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=True),
    sa.Column('difficulty_level', sa.String(length=30), nullable=False),
    sa.Column('course_type', sa.String(length=30), nullable=False),
    sa.Column('course_info', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'slug', name='uq_course_subject_slug')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_subject_id'), ['subject_id'], unique=False)

    op.create_table('problem_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('access_tier', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problem_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problem_sets_concept_id'), ['concept_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('auth_provider', sa.String(length=20), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('theme_id', sa.String(length=36), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)

    op.create_table('access_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_access_codes_created_by'), ['created_by'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('blog_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('content_html', sa.Text(), nullable=False),
    sa.Column('content_raw', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_posts_author_id'), ['author_id'], unique=False)

    op.create_table('message_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_thread_participant')
    )
    with op.batch_alter_table('message_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_participants_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_participants_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_thread_id'), ['thread_id'], unique=False)

    op.create_table('parent_link_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parent_link_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_link_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_parent_link_codes_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_link_codes_used_by'), ['used_by'], unique=False)

    op.create_table('parent_student_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student')
    )
    with op.batch_alter_table('parent_student_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_student_links_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_student_links_student_id'), ['student_id'], unique=False)

    op.create_table('problems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_set_id', sa.String(length=36), nullable=False),
    sa.Column('question_html', sa.Text(), nullable=False),
    sa.Column('question_raw', sa.Text(), nullable=False),
    sa.Column('problem_type', sa.String(length=20), nullable=False),
    sa.Column('correct_answer', sa.String(length=500), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_set_id'], ['problem_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problems_problem_set_id'), ['problem_set_id'], unique=False)

    op.create_table('student_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'concept_id', name='uq_student_concept')
    )
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_progress_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_progress_student_id'), ['student_id'], unique=False)

    op.create_table('student_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('report_month', sa.Integer(), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.String(length=36), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'report_month', 'report_year', name='uq_student_report_period')
    )
    with op.batch_alter_table('student_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_reports_generated_by'), ['generated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_reports_student_id'), ['student_id'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'slug', name='uq_topic_course_slug')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_course_id'), ['course_id'], unique=False)

    op.create_table('attempt_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('submitted_answer', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_logs_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_logs_student_id'), ['student_id'], unique=False)

    op.create_table('choices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('choice_text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_choices_problem_id'), ['problem_id'], unique=False)

    op.create_table('hints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('hint_text', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('cost_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hints_problem_id'), ['problem_id'], unique=False)

    op.create_table('resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.String(length=36), nullable=True),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('subject_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('embed_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('access_tier', sa.String(length=20), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_topic_id'), ['topic_id'], unique=False)

    op.create_table('step_by_step_solutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('problem_id', sa.String(length=36), nullable=False),
    sa.Column('steps_json', sa.JSON(), nullable=False),
    sa.Column('access_tier', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id')
    )
    op.create_table('topic_concepts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('concept_id', sa.String(length=36), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'concept_id', name='uq_topic_concept')
    )
    with op.batch_alter_table('topic_concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_concepts_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_concepts_topic_id'), ['topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_concepts_topic_id'))
        batch_op.drop_index(batch_op.f('ix_topic_concepts_concept_id'))

    op.drop_table('topic_concepts')
    op.drop_table('step_by_step_solutions')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_topic_id'))
        batch_op.drop_index(batch_op.f('ix_resources_subject_id'))
        batch_op.drop_index(batch_op.f('ix_resources_course_id'))
        batch_op.drop_index(batch_op.f('ix_resources_concept_id'))

    op.drop_table('resources')
    with op.batch_alter_table('hints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hints_problem_id'))

    op.drop_table('hints')
    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_choices_problem_id'))

    op.drop_table('choices')
    with op.batch_alter_table('attempt_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_logs_student_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_logs_problem_id'))

    op.drop_table('attempt_logs')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_course_id'))

    op.drop_table('topics')
    with op.batch_alter_table('student_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_reports_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_reports_generated_by'))

    op.drop_table('student_reports')
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_progress_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_progress_concept_id'))

    op.drop_table('student_progress')
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problems_problem_set_id'))

    op.drop_table('problems')
    with op.batch_alter_table('parent_student_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_student_links_student_id'))
        batch_op.drop_index(batch_op.f('ix_parent_student_links_parent_id'))

    op.drop_table('parent_student_links')
    with op.batch_alter_table('parent_link_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_link_codes_used_by'))
        batch_op.drop_index(batch_op.f('ix_parent_link_codes_student_id'))
        batch_op.drop_index(batch_op.f('ix_parent_link_codes_code'))

    op.drop_table('parent_link_codes')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_thread_id'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))

    op.drop_table('messages')
    with op.batch_alter_table('message_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_participants_thread_id'))

    op.drop_table('message_participants')
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_author_id'))

    op.drop_table('blog_posts')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('access_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_codes_created_by'))
        batch_op.drop_index(batch_op.f('ix_access_codes_code'))

    op.drop_table('access_codes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('problem_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_sets_concept_id'))

    op.drop_table('problem_sets')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_subject_id'))

    op.drop_table('courses')
    op.drop_table('themes')
    op.drop_table('testimonials')
    op.drop_table('subjects')
    op.drop_table('message_threads')
    op.drop_table('contact_messages')
    op.drop_table('concepts')
    # ### end Alembic commands ###
