"""add code problem fields and widen submitted_answer

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-03 01:39:59.140349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_logs', schema=None) as batch_op:
        batch_op.alter_column('submitted_answer',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('starter_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('test_harness', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rubric_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('parts_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('frq_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_column('frq_metadata')
        batch_op.drop_column('parts_json')
        batch_op.drop_column('rubric_json')
        batch_op.drop_column('test_harness')
        batch_op.drop_column('starter_code')

    with op.batch_alter_table('attempt_logs', schema=None) as batch_op:
        batch_op.alter_column('is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('submitted_answer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###
