"""add_fk_indexes

Revision ID: 2f6c51d32f8e
Revises: eec1c0de6a63
Create Date: 2026-05-28 13:15:20.879938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6c51d32f8e'
down_revision = 'eec1c0de6a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('access_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_codes_created_by'), ['created_by'], unique=False)

    with op.batch_alter_table('attempt_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_logs_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attempt_logs_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_posts_author_id'), ['author_id'], unique=False)

    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_choices_problem_id'), ['problem_id'], unique=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_subject_id'), ['subject_id'], unique=False)

    with op.batch_alter_table('hints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hints_problem_id'), ['problem_id'], unique=False)

    with op.batch_alter_table('parent_link_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parent_link_codes_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parent_link_codes_used_by'), ['used_by'], unique=False)

    with op.batch_alter_table('problem_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problem_sets_concept_id'), ['concept_id'], unique=False)

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problems_problem_set_id'), ['problem_set_id'], unique=False)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resources_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_topic_id'), ['topic_id'], unique=False)

    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_progress_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_progress_student_id'), ['student_id'], unique=False)

    with op.batch_alter_table('student_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_reports_generated_by'), ['generated_by'], unique=False)

    with op.batch_alter_table('topic_concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_concepts_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topic_concepts_topic_id'), ['topic_id'], unique=False)

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_course_id'), ['course_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_course_id'))

    with op.batch_alter_table('topic_concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_concepts_topic_id'))
        batch_op.drop_index(batch_op.f('ix_topic_concepts_concept_id'))

    with op.batch_alter_table('student_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_reports_generated_by'))

    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_progress_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_progress_concept_id'))

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_topic_id'))
        batch_op.drop_index(batch_op.f('ix_resources_subject_id'))
        batch_op.drop_index(batch_op.f('ix_resources_course_id'))
        batch_op.drop_index(batch_op.f('ix_resources_concept_id'))

    with op.batch_alter_table('problems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problems_problem_set_id'))

    with op.batch_alter_table('problem_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_sets_concept_id'))

    with op.batch_alter_table('parent_link_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parent_link_codes_used_by'))
        batch_op.drop_index(batch_op.f('ix_parent_link_codes_student_id'))

    with op.batch_alter_table('hints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hints_problem_id'))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_subject_id'))

    with op.batch_alter_table('choices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_choices_problem_id'))

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_author_id'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))

    with op.batch_alter_table('attempt_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_logs_student_id'))
        batch_op.drop_index(batch_op.f('ix_attempt_logs_problem_id'))

    with op.batch_alter_table('access_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_codes_created_by'))

    # ### end Alembic commands ###
