"""Add audit_logs table for admin action tracking

Revision ID: 5d1db32f0e28
Revises: 5274626b0773
Create Date: 2026-05-24 12:37:34.782930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d1db32f0e28'
down_revision = '5274626b0773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_codes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('access_codes_code_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_access_codes_code'))
        batch_op.create_index(batch_op.f('ix_access_codes_code'), ['code'], unique=True)

    with op.batch_alter_table('attempt_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_logs_student'))

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_posts_published'))

    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_topic_active'))
        batch_op.drop_index(batch_op.f('ix_concepts_topic_slug'))

    with op.batch_alter_table('problem_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problem_sets_concept'))

    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_progress_student'))

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_subject_slug'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_google_id_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_id'))
        batch_op.create_index(batch_op.f('ix_users_google_id'), ['google_id'], unique=False)
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('users_google_id_key'), ['google_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_subject_slug'), ['subject_id', 'slug'], unique=False)

    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_progress_student'), ['student_id'], unique=False)

    with op.batch_alter_table('problem_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problem_sets_concept'), ['concept_id', 'is_active'], unique=False)

    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_topic_slug'), ['topic_id', 'slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_concepts_topic_active'), ['topic_id', 'is_active', 'display_order'], unique=False)

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_posts_published'), ['is_published', 'published_at'], unique=False)

    with op.batch_alter_table('attempt_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_logs_student'), ['student_id', 'attempted_at'], unique=False)

    with op.batch_alter_table('access_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_codes_code'))
        batch_op.create_index(batch_op.f('ix_access_codes_code'), ['code'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('access_codes_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
