"""add messaging and reports tables

Revision ID: 6f0c429b41b0
Revises: f5f360a03978
Create Date: 2026-05-18 12:01:51.800570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0c429b41b0'
down_revision = 'f5f360a03978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_threads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id', 'user_id', name='uq_thread_participant')
    )
    with op.batch_alter_table('message_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_participants_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_participants_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['message_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_thread_id'), ['thread_id'], unique=False)

    op.create_table('student_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('report_month', sa.Integer(), nullable=False),
    sa.Column('report_year', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.String(length=36), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'report_month', 'report_year', name='uq_student_report_period')
    )
    with op.batch_alter_table('student_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_reports_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_reports_student_id'))

    op.drop_table('student_reports')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_thread_id'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))

    op.drop_table('messages')
    with op.batch_alter_table('message_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_participants_thread_id'))

    op.drop_table('message_participants')
    op.drop_table('message_threads')
    # ### end Alembic commands ###
